-- 회원관리 Database

-- 테이블명 MEMBERINFO
-- 시퀀스, 아이디(20), 비밀번호(40), 성명(20), 주소(100), 전화번호(20), 이메일(40), 사용여부(1), 권한(10)
-- 시퀀스(PK), 이메일(UNIQUE)
-- 아이디, 비밀번호, 성명, 주소, 이메일, 사용여부, 권한 NN

CREATE TABLE MEMBERINFO(
	SEQ NUMBER,
	ID VARCHAR2(20) NOT NULL,
	PASSWORD VARCHAR2(40) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	PHONE VARCHAR2(20),
	EMAIL VARCHAR2(40) NOT NULL,
	ENABLE CHAR(1) NOT NULL,
	AUTH VARCHAR(10) NOT NULL,
	CONSTRAINT MEMBERINFO_PK PRIMARY KEY(SEQ),
	CONSTRAINT MEMBERINFO_UK UNIQUE("ID","EMAIL")
);

CREATE SEQUENCE MEMEBERINFO_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM MEMBERINFO;

INSERT INTO MEMBERINFO 
(SEQ, ID, PASSWORD, NAME, ADDRESS, PHONE, EMAIL, ENABLE, AUTH)
VALUES(MEMEBERINFO_SEQ.NEXTVAL, 'HAPPY', 'HAPPY', '해피' ,'서울시' ,'114' ,'HAPPY@happy.com' ,'Y' ,'USER');

INSERT INTO MEMBERINFO 
(SEQ, ID, PASSWORD, NAME, ADDRESS, PHONE, EMAIL, ENABLE, AUTH)
VALUES(MEMEBERINFO_SEQ.NEXTVAL, 'ADMIN', 'ADMIN', '관리자' ,'서울시' ,'111' ,'admin@info.com' ,'Y' ,'ADMIN');

INSERT INTO MEMBERINFO 
(SEQ, ID, PASSWORD, NAME, ADDRESS, PHONE, EMAIL, ENABLE, AUTH)
VALUES(MEMEBERINFO_SEQ.NEXTVAL, 'USER', 'USER', '사용자' ,'서울시' ,'110' ,'user@naver.com' ,'N' ,'USER');


